// Generated by scripts/sync-home-previews.mjs from labs-src/mathematics/circle-theorem-constraint-network/lab.html.
// Source rendering functions are preserved; only UI orchestration outside the excerpt is omitted.
export function mount(root) {
const update=(()=>{
const $ = id => root.getElementById('home-circle-' + id);

const svg=$('geometry');
const TAU=Math.PI*2, DEG=180/Math.PI, RAD=Math.PI/180;
const EXACT_DEG=.02;
const O={x:410,y:362}, R=245;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const norm=a=>((a%TAU)+TAU)%TAU;
const sdiff=(a,b)=>{let d=norm(a-b);if(d>Math.PI)d-=TAU;return d};
const fmt=(v,d=1)=>Number(v).toFixed(d).replace(/\.0$/,'');
const esc=s=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const pt=(a,r=R)=>({x:O.x+r*Math.cos(a),y:O.y-r*Math.sin(a)});
const dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
const unit=(a,b)=>{const d=dist(a,b)||1;return{x:(b.x-a.x)/d,y:(b.y-a.y)/d}};
const screenVecAngle=(v,p)=>norm(Math.atan2(v.y-p.y,p.x-v.x));
function angleAt(v,p1,p2){const a={x:p1.x-v.x,y:p1.y-v.y},b={x:p2.x-v.x,y:p2.y-v.y},da=Math.hypot(a.x,a.y)||1,db=Math.hypot(b.x,b.y)||1;return Math.acos(clamp((a.x*b.x+a.y*b.y)/(da*db),-1,1))*DEG}

function svgLine(a,b,cls,extra=''){return `<line x1="${a.x}" y1="${a.y}" x2="${b.x}" y2="${b.y}" class="${cls}" ${extra}/>`}
function svgCircle(p,r,cls,extra=''){return `<circle cx="${p.x}" cy="${p.y}" r="${r}" class="${cls}" ${extra}/>`}
function svgText(p,text,cls='label',anchor='middle'){return `<text x="${p.x}" y="${p.y}" text-anchor="${anchor}" class="${cls}">${esc(text)}</text>`}
function mathArcPoints(center,r,a0,a1,steps=20){let d=sdiff(a1,a0);const pts=[];for(let i=0;i<=steps;i++){const a=a0+d*i/steps;pts.push({x:center.x+r*Math.cos(a),y:center.y-r*Math.sin(a)})}return pts}
function arcPath(center,r,a0,a1,steps=20){const pts=mathArcPoints(center,r,a0,a1,steps);return 'M '+pts.map(p=>`${p.x.toFixed(2)} ${p.y.toFixed(2)}`).join(' L ')}
function wedge(v,p1,p2,r,cls,label){const a0=screenVecAngle(v,p1),a1=screenVecAngle(v,p2);const d=sdiff(a1,a0),am=a0+d/2,path=arcPath(v,r,a0,a1,18),lp={x:v.x+(r+18)*Math.cos(am),y:v.y-(r+18)*Math.sin(am)};return `<path d="${path}" class="wedge ${cls}"/>${label?svgText(lp,label,'angle-value'):''}`}
function rightMark(v,p1,p2,size=15,cls='right-angle'){const u1=unit(v,p1),u2=unit(v,p2),a={x:v.x+u1.x*size,y:v.y+u1.y*size},b={x:a.x+u2.x*size,y:a.y+u2.y*size},c={x:v.x+u2.x*size,y:v.y+u2.y*size};return `<path d="M ${a.x} ${a.y} L ${b.x} ${b.y} L ${c.x} ${c.y}" class="${cls}"/>`}
function grid(){let s='';for(let x=80;x<=740;x+=55)s+=`<line x1="${x}" y1="55" x2="${x}" y2="670" class="grid-line"/>`;for(let y=62;y<=667;y+=55)s+=`<line x1="72" y1="${y}" x2="748" y2="${y}" class="grid-line"/>`;return s}
function outerTraceSegment(a0,a1,cls,r=R+18){return `<path d="${arcPath(O,r,a0,a1,6)}" class="trace ${cls}"/>`}
function trace90(A,B){let s='';const n=60,w=TAU/n*.72;for(let i=0;i<n;i++){const a=TAU*i/n;if(Math.abs(sdiff(a,A))<8*RAD||Math.abs(sdiff(a,B))<8*RAD){s+=outerTraceSegment(a-w/2,a+w/2,'muted');continue}const q=pt(a),v=angleAt(q,pt(A),pt(B));const cls=Math.abs(v-90)<=EXACT_DEG?'good':v<90?'low':'high';s+=outerTraceSegment(a-w/2,a+w/2,cls)}return s}
function pointLabel(p,name,dx=12,dy=-12,cls='label'){return svgText({x:p.x+dx,y:p.y+dy},name,cls,'start')}
function renderBase(){return `${grid()}<circle cx="${O.x}" cy="${O.y}" r="${R}" class="circle-main"/>${svgCircle(O,5,'centre-dot')}${svgText({x:O.x+11,y:O.y-10},'O','label small','start')}`}
function rng(seed){let v=seed>>>0;return()=>{v=(Math.imul(v,1664525)+1013904223)>>>0;return v/4294967296}}
function pick(r,a){return a[Math.floor(r()*a.length)]}
function safeAngle(r){return pick(r,[18,42,68,112,156,202,246,292,334])*RAD}
const r=rng(1),p={};
     const alpha=pick(r,[25,30,35,40,45,50,55,60,65]),A=safeAngle(r),targetB=norm(A+Math.PI),D=norm(targetB+2*alpha*RAD),offset=pick(r,[-38,-30,-24,24,30,38])*RAD;
     let C=norm(targetB+pick(r,[72,86,102,118])*RAD);if(Math.abs(sdiff(C,D))<18*RAD)C=norm(C+34*RAD);
     Object.assign(p,{alpha,answer:90-alpha,A,targetB,D,C,startB:norm(targetB+offset),reason:'angle in a semicircle = 90°',reasonRule:'semicircle',prompt:`Repair AB so it is a diameter. In the repaired diagram, ∠DAB = ${alpha}°. Find x = ∠ABD.`,visualTitle:'Right-angle trigger · diameter',visualHint:'B changes the structure. C is the stress-test point; D is the fixed calculation point.',realisation:'The diameter supplies the 90°. The subtraction is ordinary triangle angle sum.'});
   
const travel=96*RAD,startC=norm(p.D+travel);
const s={B:p.targetB,C:startC,testTravel:0,alignedOnce:true},current=()=>p,session=()=>s;
function semicircleGeometry(){const p=current(),s=session(),A=pt(p.A),B=pt(s.B),C=pt(s.C),D=pt(p.D),ang=angleAt(C,A,B),diamErr=Math.abs(Math.abs(sdiff(s.B,p.A))-Math.PI)*DEG,aligned=diamErr<=EXACT_DEG;if(!aligned)s.testTravel=0;else if(!s.alignedOnce){s.alignedOnce=true;s.testTravel=0}const tested=s.testTravel>38*RAD;s.geometryReady=aligned&&tested;
 let g=renderBase()+trace90(p.A,s.B)+svgLine(A,B,aligned?'diameter':'chord-a')+svgLine(O,A,'radius')+svgLine(O,B,'radius')+svgLine(C,A,'construction')+svgLine(C,B,'construction');g+=wedge(C,A,B,42,Math.abs(ang-90)<1.5?'good':'a',`${fmt(ang,1)}°`);if(Math.abs(ang-90)<1.5)g+=rightMark(C,A,B,13);g+=svgCircle(A,8,'fixed-point')+pointLabel(A,'A',10,-12,'label a')+svgCircle(B,10,'drag-point b','data-drag="p0b"')+pointLabel(B,'B',10,-12,'label b')+svgCircle(C,10,'drag-point c','data-drag="p0c"')+pointLabel(C,'C',10,-12,'label c');
 if(aligned){g+=svgLine(D,A,'construction')+svgLine(D,B,'construction')+svgCircle(D,7,'ghost-point')+pointLabel(D,'D',9,-10,'label gold')+rightMark(D,A,B,12)+wedge(A,D,B,31,'gold',`${p.alpha}°`)+wedge(B,A,D,31,'a','x')+svgText({x:O.x,y:O.y+R+34},`calculation triangle: ∠DAB = ${p.alpha}°`,'stage-note')}
 g+=svgText({x:O.x,y:O.y-R-32},'outer sweep: ∠ACB as C moves','stage-note');svg.innerHTML=g;}
svg.style.setProperty('--lab-chart-text-size','14px');
semicircleGeometry();
// Replay a single drag along the circumference, then release C exactly at D.
// Keep the native geometry intact when the two points coincide.
return time=>{const progress=clamp((time-1700)/4800,0,1),eased=progress*progress*(3-2*progress);
  s.C=progress===1?p.D:norm(startC-travel*eased);s.testTravel=travel*eased;semicircleGeometry();};

})();
let lastTime;
return time=>{if(time===lastTime)return;lastTime=time;root.host.style.setProperty('--preview-animation-time',String(time));update(time);};
}
