// Generated by scripts/sync-home-previews.mjs from labs-src/computer-science/fetch-decode-execute/lab.html.
// Source rendering functions are preserved; only UI orchestration outside the excerpt is omitted.
export function mount(root) {
const update=(()=>{
const $ = id => root.getElementById('home-cpu-' + id);

const isSimpleMode=()=>true;
const currentProgram=()=>({simpleLabels:{0:'I1',1:'I2',2:'I3',3:'I4',10:'RESULT'}});
let state, currentInstruction, microQueue;
const memory={0:'LOADI 8'};
// External RAM/bus presentation is outside the crop. CPU paths still replay unchanged.
const activateBus=()=>{};
const highlightRam=()=>{};
function displayAddress(address){
    if(address===null||address===undefined)return "—";
    if(!isSimpleMode())return String(address);
    return currentProgram().simpleLabels[address] || `L${address}`;
  }
function isInstruction(value){
    return typeof value==="string" && /^(LDA|ADD|SUB|STA|HLT|LOADI|ADDI|SUBI|STORE|STOP)/.test(value);
  }
function displayInstruction(text){
    if(!isInstruction(text))return String(text);
    if(!isSimpleMode())return text;
    if(text==="STOP")return "STOP";
    const [op,arg]=String(text).split(/\s+/);
    if(op==="LOADI")return `LOAD ${arg}`;
    if(op==="ADDI")return `ADD ${arg}`;
    if(op==="SUBI")return `SUBTRACT ${arg}`;
    if(op==="STORE")return "STORE result";
    return text;
  }
function visibleOp(op){
    if(!isSimpleMode())return op;
    return {LOADI:"LOAD",ADDI:"ADD",SUBI:"SUBTRACT",STORE:"STORE",STOP:"STOP"}[op]||op;
  }
function visibleDecodedInstruction(instruction){
    if(!instruction)return "";
    if(!isSimpleMode())return `${instruction.op}${instruction.arg!==null?" "+instruction.arg:""}`;
    if(instruction.op==="STOP")return "STOP";
    if(instruction.op==="STORE")return "STORE result";
    return `${visibleOp(instruction.op)} ${instruction.arg}`;
  }
function parseInstruction(text){
    if(text==="HLT"||text==="STOP")return {op:text,arg:null};
    const [op,argText]=String(text).split(/\s+/);
    return {op,arg:Number(argText)};
  }
function clearHighlights(){
    root.querySelectorAll(".cpu-svg .box,.cpu-svg .logic,.data-path,.control-path,.clock-path,.ram-row,.bus-lane")
      .forEach(el=>el.classList.remove("active","changed","to-ram","to-cpu"));
    root.querySelectorAll(".bus-value").forEach(el=>{el.textContent="";});
  }
function highlightComponent(id,changed=false){
    const group=$(id);
    if(!group)return;
    const shape=group.querySelector(".box,.logic")||group;
    shape.classList.add(changed?"changed":"active");
  }
function activatePath(id){
    const el=$(id);
    if(el)el.classList.add("active");
  }
function activateControl(target){
    const id={ALU:"wireCtrlAlu",ACC:"wireCtrlAcc",MDR:"wireCtrlMdr",CIR:"wireCtrlCir",PC:"wireCtrlPc",MAR:"wireCtrlMar"}[target];
    if(id)activatePath(id);
  }
function displayRegister(value,name){
    if(value===null||value===undefined)return "—";
    if((name==="MDR"||name==="CIR")&&isInstruction(value))return displayInstruction(value);
    return String(value);
  }
function fitSvgText(el){
    if(!el)return;
    const max=el.id.replace("home-cpu-", "")==="mdrValue"?132:el.id.replace("home-cpu-", "")==="cirValue"?142:110;
    let size=19;
    el.style.fontSize=size+"px";
    try{
      while(el.getComputedTextLength()>max&&size>10){
        size-=1;
        el.style.fontSize=size+"px";
      }
    }catch{}
  }
function renderRegisters(){
    $("pcValue").textContent=displayAddress(state.PC);
    $("marValue").textContent=displayAddress(state.MAR);
    $("mdrValue").textContent=displayRegister(state.MDR,"MDR");
    $("cirValue").textContent=displayRegister(state.CIR,"CIR");
    $("accValue").textContent=displayRegister(state.ACC);
    $("cuValue").textContent=state.CU;
    $("aluValue").textContent=state.ALU;
    ["pcValue","marValue","mdrValue","cirValue","accValue"].forEach(id=>fitSvgText($(id)));
  }
function enqueueFetch(){
    microQueue=[
      {
        phase:"fetch",
        title:"MAR ← PC",
        note:"Copy the next instruction location from PC into MAR.",
        apply(){
          state.MAR=state.PC;
          highlightComponent("regPC");
          highlightComponent("regMAR",true);
          activateControl("PC");
          activateControl("MAR");
          activatePath("wirePcMar");
        }
      },
      {
        phase:"fetch",
        title:isSimpleMode()?"PC → next instruction":"PC ← PC + 1",
        note:isSimpleMode()
          ?"Advance PC to the next symbolic instruction location."
          :"Increment PC so it points to the next instruction.",
        apply(){
          state.PC+=1;
          highlightComponent("regPC",true);
          activateControl("PC");
        }
      },
      {
        phase:"fetch",
        title:"Address + READ → RAM",
        note:"MAR drives the address bus while the CU sends READ on the control bus.",
        apply(){
          highlightComponent("regMAR");
          highlightComponent("unitCU");
          activateControl("MAR");
          activatePath("wireMarAddress");
          activatePath("wireCuControl");
          activateBus("addressBus",displayAddress(state.MAR),"to-ram");
          activateBus("controlBus","READ","to-ram");
          highlightRam(state.MAR);
        }
      },
      {
        phase:"fetch",
        title:"MDR ← RAM[MAR]",
        note:"RAM returns the instruction on the data bus and MDR receives it.",
        apply(){
          state.MDR=memory[state.MAR];
          highlightRam(state.MAR);
          highlightComponent("regMDR",true);
          activateControl("MDR");
          activatePath("wireMdrData");
          activateBus("dataBus",displayInstruction(state.MDR),"to-cpu");
        }
      },
      {
        phase:"fetch",
        title:"CIR ← MDR",
        note:"Copy the fetched instruction from MDR into CIR.",
        apply(){
          state.CIR=state.MDR;
          highlightComponent("regMDR");
          highlightComponent("regCIR",true);
          activateControl("MDR");
          activateControl("CIR");
          activatePath("wireMdrCir");
        }
      },
      {
        phase:"decode",
        title:"CU decodes CIR",
        note:"CIR supplies the instruction to the decoder in the Control Unit.",
        apply(){
          currentInstruction=parseInstruction(state.CIR);
          state.CU=visibleDecodedInstruction(currentInstruction);
          highlightComponent("regCIR");
          highlightComponent("unitCU",true);
          activatePath("wireCirCu");
        }
      }
    ];
  }
// Exact shared lab value-surface fitting, driven synchronously by the preview clock.
const values=[...root.querySelectorAll('svg text[data-lab-value]')].map(value=>{
  let surface=value.previousElementSibling;
  if(!surface?.classList.contains('lab-svg-value-surface')){surface=document.createElementNS('http://www.w3.org/2000/svg','rect');surface.setAttribute('class','lab-svg-value-surface');surface.setAttribute('rx','5');surface.setAttribute('aria-hidden','true');value.before(surface);}
  return {value,surface};
});
function fitValues(){for(const {value,surface} of values){value.style.removeProperty('--lab-value-fit-size');const css=getComputedStyle(value),px=Number(css.getPropertyValue('--lab-value-padding-x'))||7,py=Number(css.getPropertyValue('--lab-value-padding-y'))||3;let b=value.getBBox();const component=[...value.parentElement.children].find(el=>el.tagName==='rect'&&!el.classList.contains('lab-svg-value-surface'));if(component){const box=component.getBBox(),centre=b.x+b.width/2,available=2*Math.min(centre-box.x,box.x+box.width-centre)-2*px-8;if(available>0&&b.width>available){value.style.setProperty('--lab-value-fit-size',parseFloat(css.fontSize)*available/b.width+'px');b=value.getBBox();}}Object.entries({x:b.x-px,y:b.y-py,width:b.width+2*px,height:b.height+2*py}).forEach(([k,v])=>surface.setAttribute(k,v));}}
function enqueueExecute(){const {op,arg}=currentInstruction;if(op==="LOADI"){
      microQueue.push({
        phase:"execute",
        title:"ACC ← CIR value",
        note:`${displayInstruction(state.CIR)} is immediate: ${arg} comes directly from CIR, so RAM is not read again.`,
        apply(){
          state.ACC=arg;
          highlightComponent("regCIR");
          highlightComponent("regACC",true);
          activateControl("CIR");
          activateControl("ACC");
          activatePath("wireCirAcc");
        }
      });
      return;
    }

    }
let completed=-1;
function reset(){state={PC:0,MAR:null,MDR:null,CIR:null,ACC:0,CU:'waiting',ALU:'idle'};currentInstruction=null;microQueue=[];completed=-1;clearHighlights();renderRegisters();fitValues();enqueueFetch();}
reset();
return time=>{const target=Math.max(-1,Math.min(6,Math.floor((time-1400)/1150)));if(target<completed)reset();while(completed<target){if(!microQueue.length)enqueueExecute();clearHighlights();microQueue.shift().apply();activatePath('wireClockCu');renderRegisters();fitValues();completed++;}};

})();
let lastTime;
return time=>{if(time===lastTime)return;lastTime=time;root.host.style.setProperty('--preview-animation-time',String(time));update(time);};
}
