// Generated by scripts/sync-home-previews.mjs from labs-src/physics/diffraction-through-a-gap/lab.html.
// Source rendering functions are preserved; only UI orchestration outside the excerpt is omitted.
export function mount(root) {
const update=(()=>{
const $ = id => root.getElementById('home-diffraction-' + id);

const clamp=(v,a,b)=>Math.min(b,Math.max(a,v)),fmt=(v,d=1)=>Number(v).toFixed(d);
const STAGE_W = 900;
  const STAGE_H = 430;
  const BARRIER_X = 350;
  const CENTRE_Y = 215;
  const PX_PER_CM = 42;

const state={phase:'gap',gap:3.6,lambda:1.6,fieldDirty:true,animationPhase:0};
const canvas = $("waveCanvas");
  const ctx = canvas.getContext("2d", { alpha: false });
  const simCanvas = document.createElement("canvas");
  const SIM_W = 360;
  const SIM_H = 172;
  simCanvas.width = SIM_W;
  simCanvas.height = SIM_H;
  const simCtx = simCanvas.getContext("2d", { alpha: false });
  const image = simCtx.createImageData(SIM_W, SIM_H);
  const phases = new Float32Array(SIM_W * SIM_H);
  const amplitudes = new Float32Array(SIM_W * SIM_H);
  const SIM_BARRIER_X = BARRIER_X / STAGE_W * SIM_W;
  const SIM_PX_PER_CM = PX_PER_CM / STAGE_W * SIM_W;


function spreadAngle(gap = state.gap, lambda = state.lambda) {
    return Math.asin(Math.min(0.999, lambda / gap)) * 180 / Math.PI;
  }
function smoothstep(min, max, value) {
    const t = clamp((value - min) / (max - min || 1), 0, 1);
    return t * t * (3 - 2 * t);
  }
function computeField() {
    const k = Math.PI * 2 / state.lambda;
    const curvature = clamp(state.lambda / state.gap * 1.08, 0.08, 1);
    const thetaZero = Math.asin(Math.min(0.999, state.lambda / state.gap));
    let index = 0;
    for (let py = 0; py < SIM_H; py += 1) {
      const yCm = (py - SIM_H / 2) / SIM_PX_PER_CM;
      for (let px = 0; px < SIM_W; px += 1, index += 1) {
        const xCm = (px - SIM_BARRIER_X) / SIM_PX_PER_CM;
        if (px <= SIM_BARRIER_X) {
          phases[index] = k * xCm;
          amplitudes[index] = 0.9;
          continue;
        }
        const xSafe = Math.max(0.025, xCm);
        const theta = Math.atan2(yCm, xSafe + 0.16);
        const z = Math.PI * state.gap * Math.sin(theta) / state.lambda;
        const sinc = Math.abs(z) < 0.00001 ? 1 : Math.sin(z) / z;
        let amplitude = Math.pow(Math.abs(sinc), 0.58);
        const beyondMain = Math.max(0, Math.abs(theta) - thetaZero);
        if (beyondMain > 0) amplitude *= 0.18 * Math.exp(-beyondMain * 2.4);
        const outsideOpening = Math.max(0, Math.abs(yCm) - state.gap / 2);
        if (outsideOpening > 0) {
          amplitude *= 0.08 + 0.92 * smoothstep(0, outsideOpening * 1.35 + 0.38, xSafe);
        }
        const sourceOffset = 0.52;
        const waveDistance = Math.sqrt((xSafe + sourceOffset) ** 2 + (curvature * yCm) ** 2) - sourceOffset;
        phases[index] = k * waveDistance;
        amplitudes[index] = clamp(amplitude, 0, 1);
      }
    }
    state.fieldDirty = false;
  }
function renderWaveField() {
    if (state.fieldDirty) computeField();
    const data = image.data;
    const time = state.animationPhase;
    for (let index = 0, p = 0; index < phases.length; index += 1, p += 4) {
      const amp = amplitudes[index];
      const wave = Math.cos(phases[index] - time);
      const crest = Math.pow(Math.max(0, wave), 7) * amp;
      const trough = Math.pow(Math.max(0, -wave), 4) * amp;
      const texture = 0.8 * Math.sin(index * 0.071) + 0.55 * Math.sin(index * 0.019);
      data[p] = clamp(226 + crest * 28 - trough * 26 + texture, 0, 255);
      data[p + 1] = clamp(242 + crest * 12 - trough * 25 + texture, 0, 255);
      data[p + 2] = clamp(248 + crest * 5 - trough * 15 + texture * 0.5, 0, 255);
      data[p + 3] = 255;
    }
    simCtx.putImageData(image, 0, 0);
    ctx.save();
    ctx.imageSmoothingEnabled = true;
    ctx.drawImage(simCanvas, 0, 0, STAGE_W, STAGE_H);
    const gradient = ctx.createLinearGradient(0, 0, 0, STAGE_H);
    gradient.addColorStop(0, "rgba(255,255,255,.13)");
    gradient.addColorStop(.52, "rgba(255,255,255,0)");
    gradient.addColorStop(1, "rgba(44,104,132,.08)");
    ctx.fillStyle = gradient;
    ctx.fillRect(0, 0, STAGE_W, STAGE_H);
    ctx.restore();
  }
function fanGeometry(angleDegrees) {
    const theta = angleDegrees * Math.PI / 180;
    const tan = Math.tan(theta);
    const rightX = 886;
    const topLimit = 12;
    const bottomLimit = STAGE_H - 12;
    const dx = rightX - BARRIER_X;
    let topX = rightX;
    let topY = CENTRE_Y - tan * dx;
    if (topY < topLimit) {
      topY = topLimit;
      topX = BARRIER_X + (CENTRE_Y - topLimit) / Math.max(tan, 0.0001);
    }
    let bottomX = rightX;
    let bottomY = CENTRE_Y + tan * dx;
    if (bottomY > bottomLimit) {
      bottomY = bottomLimit;
      bottomX = BARRIER_X + (bottomLimit - CENTRE_Y) / Math.max(tan, 0.0001);
    }
    const radius = 76;
    const topArc = { x: BARRIER_X + radius * Math.cos(theta), y: CENTRE_Y - radius * Math.sin(theta) };
    const bottomArc = { x: BARRIER_X + radius * Math.cos(theta), y: CENTRE_Y + radius * Math.sin(theta) };
    return { topX, topY, bottomX, bottomY, topArc, bottomArc, radius };
  }
function updateFan() {
    const current = fanGeometry(spreadAngle());
    $("fanFill").setAttribute("d", `M ${BARRIER_X} ${CENTRE_Y} L ${current.topX} ${current.topY} L ${current.bottomX} ${current.bottomY} Z`);
    $("fanTop").setAttribute("d", `M ${BARRIER_X} ${CENTRE_Y} L ${current.topX} ${current.topY}`);
    $("fanBottom").setAttribute("d", `M ${BARRIER_X} ${CENTRE_Y} L ${current.bottomX} ${current.bottomY}`);
    $("fanArc").setAttribute("d", `M ${current.topArc.x} ${current.topArc.y} A ${current.radius} ${current.radius} 0 0 1 ${current.bottomArc.x} ${current.bottomArc.y}`);

    if (state.phase === "compare") {
      const reference = fanGeometry(spreadAngle(REFERENCE.gap, REFERENCE.lambda));
      $("referenceFill").setAttribute("d", `M ${BARRIER_X} ${CENTRE_Y} L ${reference.topX} ${reference.topY} L ${reference.bottomX} ${reference.bottomY} Z`);
      $("referenceTop").setAttribute("d", `M ${BARRIER_X} ${CENTRE_Y} L ${reference.topX} ${reference.topY}`);
      $("referenceBottom").setAttribute("d", `M ${BARRIER_X} ${CENTRE_Y} L ${reference.bottomX} ${reference.bottomY}`);
      $("referenceArc").setAttribute("d", `M ${reference.topArc.x} ${reference.topArc.y} A ${reference.radius} ${reference.radius} 0 0 1 ${reference.bottomArc.x} ${reference.bottomArc.y}`);
    }
  }
function updateBarrier() {
    const half = state.gap * PX_PER_CM / 2;
    const top = CENTRE_Y - half;
    const bottom = CENTRE_Y + half;
    $("barrierTop").setAttribute("height", Math.max(0, top));
    $("barrierBottom").setAttribute("y", bottom);
    $("barrierBottom").setAttribute("height", Math.max(0, STAGE_H - bottom));
    for (const id of ["gapEdgeTop", "gapTopHandle"]) {
      const node = $(id);
      if (node.tagName.toLowerCase() === "line") { node.setAttribute("y1", top); node.setAttribute("y2", top); }
      else node.querySelectorAll("circle").forEach(circle => circle.setAttribute("cy", top));
    }
    for (const id of ["gapEdgeBottom", "gapBottomHandle"]) {
      const node = $(id);
      if (node.tagName.toLowerCase() === "line") { node.setAttribute("y1", bottom); node.setAttribute("y2", bottom); }
      else node.querySelectorAll("circle").forEach(circle => circle.setAttribute("cy", bottom));
    }
    $("gapTopHandle").setAttribute("aria-valuenow", fmt(state.gap, 1));
    $("gapBottomHandle").setAttribute("aria-valuenow", fmt(state.gap, 1));
    $("gapLabelBg").setAttribute("y", CENTRE_Y - 13);
    $("gapLabel").setAttribute("y", CENTRE_Y + 4);
    $("gapLabel").textContent = `gap ${fmt(state.gap, 1)} cm`;

    const stripeHost = $("barrierStripes");
    stripeHost.replaceChildren();
    for (let y = 12; y < STAGE_H; y += 22) {
      if (y > top - 9 && y < bottom + 9) continue;
      const line = document.createElementNS("http://www.w3.org/2000/svg", "line");
      line.setAttribute("class", "barrier-stripe");
      line.setAttribute("x1", 343);
      line.setAttribute("x2", 357);
      line.setAttribute("y1", y);
      line.setAttribute("y2", y + 7);
      stripeHost.appendChild(line);
    }
  }
function updateWavelengthMeasure() {
    const startX = 84;
    const endX = startX + state.lambda * PX_PER_CM;
    $("lambdaLine").setAttribute("x2", endX);
    $("lambdaCapEnd").setAttribute("x1", endX);
    $("lambdaCapEnd").setAttribute("x2", endX);
    $("lambdaHalo").setAttribute("cx", endX);
    $("lambdaHandle").setAttribute("cx", endX);
    $("lambdaMeasure").setAttribute("aria-valuenow", fmt(state.lambda, 1));
    const outStart = 504;
    const outEnd = outStart + state.lambda * PX_PER_CM;
    $("outLambdaLine").setAttribute("x2", outEnd);
    $("outLambdaCapEnd").setAttribute("x1", outEnd);
    $("outLambdaCapEnd").setAttribute("x2", outEnd);
  }
$('overlay').style.setProperty('--lab-chart-text-size','11px');
updateBarrier();updateFan();updateWavelengthMeasure();
$('lambdaGripValue').textContent='λ = '+fmt(state.lambda)+' cm';
$('gapGuide').hidden=true;$('waveGuide').hidden=true;
// Preserve the original ripple-tank renderer and its propagation speed.
return time=>{
  const gap=Math.round((3.6-2.4*clamp((time-500)/6500,0,1))*10)/10;
  if(gap!==state.gap){state.gap=gap;state.fieldDirty=true;updateBarrier();updateFan();}
  state.animationPhase=time*.0042;renderWaveField();
};

})();
let lastTime;
return time=>{if(time===lastTime)return;lastTime=time;root.host.style.setProperty('--preview-animation-time',String(time));update(time);};
}
