// Generated by scripts/sync-home-previews.mjs from labs-src/physics/gas-compression-at-constant-temperature/lab.html.
// Source rendering functions are preserved; only UI orchestration outside the excerpt is omitted.
export function mount(root) {
const update=(()=>{
const $ = id => root.getElementById('home-gas-' + id);

const NS='http://www.w3.org/2000/svg';
  const clamp=(v,a,b)=>Math.min(b,Math.max(a,v));
  const fmt=(v,d=0)=>Number(v).toFixed(d);
  const K=600;
  const MIN_V=2,MAX_V=8,MIN_P=60,MAX_P=300;
  const INNER_LEFT=104,PISTON_MIN=252,PISTON_MAX=660,TOP=112,BOTTOM=294;
  const GRAPH={x:101,y:420,w:620,h:145};
  const GAUGE={cx:870,cy:184,r:78};
  const CASES=[
    {id:'compress',label:'Compression',startV:6,targetV:3,expect:'increase',title:'Predict what happens when the gas volume is halved.',hint:'Record a prediction first. Then move the piston to 3.00 L and use the physical evidence.',phase:'Predict → test',question:'When volume decreases from 6.00 L to 3.00 L, what will happen to the pressure?',choices:[['decrease','Pressure decreases'],['same','Pressure stays the same'],['increase','Pressure increases']]},
    {id:'expand',label:'Expansion',startV:3,targetV:6,expect:'decrease',title:'Test the relationship in the opposite direction.',hint:'Predict first, then expand the same gas to 6.00 L. Does the earlier relationship reverse?',phase:'Predict → counterexample',question:'When volume increases from 3.00 L to 6.00 L, what will happen to the pressure?',choices:[['decrease','Pressure decreases'],['same','Pressure stays the same'],['increase','Pressure increases']]},
    {id:'gauge',label:'Gauge target',startV:5,targetP:150,targetV:4,expect:'decrease',title:'Reach 150 kPa without being told the volume.',hint:'Choose how the volume must change, then use the gauge as the target and the particles as the explanation.',phase:'Reason → control',question:'Pressure must rise from 120 kPa to 150 kPa. What must happen to the gas volume?',choices:[['decrease','Volume must decrease'],['same','Volume must stay the same'],['increase','Volume must increase']]},
    {id:'working',label:'Practice',startV:7.5,targetV:2.5,targetP:240,expect:null,title:'Calculate the pressure, place your marker, then test it.',hint:'Use p₁V₁ = p₂V₂. A wrong marker still stays on the gauge and graph so the experiment can expose the mismatch.',phase:'Calculate → test',working:true,generated:true}
  ];
  const state={caseIndex:0,volume:6,prediction:null,drag:null,solved:[false,false,false,false],trace:[],particles:[],flashes:[],lastTime:0,workingLevel:0,markerP:null,markerV:null,markerPlaced:false,work:{product:'',pressure:'',volume:''},free:false,freeStartV:6,pins:[],pulsePhase:0,practiceNumber:0,practiceSeed:9348571,lastPracticePair:'',practiceLevel:2};
  const c=()=>CASES[state.caseIndex];

const pressure=v=>K/v;
  const impactRate=v=>72/v;
  const volumeToX=v=>PISTON_MIN+(v-MIN_V)/(MAX_V-MIN_V)*(PISTON_MAX-PISTON_MIN);
  const graphX=v=>GRAPH.x+(v-MIN_V)/(MAX_V-MIN_V)*GRAPH.w;
  const graphY=p=>GRAPH.y+GRAPH.h-(p-MIN_P)/(MAX_P-MIN_P)*GRAPH.h;
  const gaugeAngle=p=>200+(clamp(p,MIN_P,MAX_P)-MIN_P)/(MAX_P-MIN_P)*140;
  const polar=(cx,cy,r,deg)=>{const a=deg*Math.PI/180;return{x:cx+Math.cos(a)*r,y:cy+Math.sin(a)*r}};
  const svg=(tag,attrs={})=>{const el=document.createElementNS(NS,tag);for(const[k,v]of Object.entries(attrs))el.setAttribute(k,v);return el};
  const setAttrs=(el,attrs)=>{for(const[k,v]of Object.entries(attrs))el.setAttribute(k,v)};

let seed=42;function random(){seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296;}
function initStatic(){
    const scale=$('volumeScale');
    for(let v=2;v<=8;v++){
      const x=volumeToX(v);scale.append(svg('line',{x1:x,y1:326,x2:x,y2:v%2===0?339:335,stroke:'#74828a','stroke-width':v%2===0?2:1}));
      const t=svg('text',{x,y:351,'text-anchor':'middle',fill:'#627078','font-size':'8','font-weight':'760'});t.textContent=v;scale.append(t);
    }
    const ticks=$('gaugeTicks');
    for(let p=60;p<=300;p+=20){const a=gaugeAngle(p),a1=polar(GAUGE.cx,GAUGE.cy,p%60===0?68:72,a),a2=polar(GAUGE.cx,GAUGE.cy,84,a);ticks.append(svg('line',{x1:a1.x,y1:a1.y,x2:a2.x,y2:a2.y,class:`gauge-tick ${p%60===0?'major':''}`}));if(p%60===0){const q=polar(GAUGE.cx,GAUGE.cy,56,a),t=svg('text',{x:q.x,y:q.y+3.5,'text-anchor':'middle',fill:'#4f5d66','font-size':'9','font-weight':'820'});t.textContent=p;ticks.append(t)}}
    const grid=$('graphGrid');
    for(let v=2;v<=8;v++){const x=graphX(v);grid.append(svg('line',{x1:x,y1:GRAPH.y,x2:x,y2:GRAPH.y+GRAPH.h,class:'graph-grid'}));const t=svg('text',{x,y:GRAPH.y+GRAPH.h+17,'text-anchor':'middle',fill:'#748189','font-size':'7.5'});t.textContent=v;grid.append(t)}
    for(let p=60;p<=300;p+=60){const y=graphY(p);grid.append(svg('line',{x1:GRAPH.x,y1:y,x2:GRAPH.x+GRAPH.w,y2:y,class:'graph-grid'}));const t=svg('text',{x:GRAPH.x-8,y:y+3,'text-anchor':'end',fill:'#748189','font-size':'7.5'});t.textContent=p;grid.append(t)}
    grid.append(svg('line',{x1:GRAPH.x,y1:GRAPH.y,x2:GRAPH.x,y2:GRAPH.y+GRAPH.h,class:'graph-axis'}));grid.append(svg('line',{x1:GRAPH.x,y1:GRAPH.y+GRAPH.h,x2:GRAPH.x+GRAPH.w,y2:GRAPH.y+GRAPH.h,class:'graph-axis'}));
    let tx=svg('text',{x:GRAPH.x+GRAPH.w/2,y:GRAPH.y+GRAPH.h+31,'text-anchor':'middle',fill:'#65737b','font-size':'8','font-weight':'800'});tx.textContent='volume / L';grid.append(tx);
    let ty=svg('text',{x:58,y:GRAPH.y+GRAPH.h/2,'text-anchor':'middle',fill:'#65737b','font-size':'8','font-weight':'800',transform:`rotate(-90 58 ${GRAPH.y+GRAPH.h/2})`});ty.textContent='pressure / kPa';grid.append(ty);
    let d='';for(let v=2;v<=8.001;v+=.04)d+=`${d?'L':'M'}${graphX(v).toFixed(2)} ${graphY(pressure(v)).toFixed(2)} `;$('graphCurve').setAttribute('d',d);
    const impacts=$('impactPulses');for(let i=0;i<18;i++){const x=800+i*10.25;const pulse=svg('circle',{cx:x,cy:452,r:3.2,class:'impact-pulse'});impacts.append(pulse)}
    const particleLayer=$('particleLayer');
    for(let i=0;i<18;i++){const angle=(i*137.5%360)*Math.PI/180,speed=74;const p={x:INNER_LEFT+24+random()*420,y:TOP+17+random()*(BOTTOM-TOP-34),vx:Math.cos(angle)*speed,vy:Math.sin(angle)*speed,el:svg('circle',{r:5,class:'particle'})};state.particles.push(p);particleLayer.append(p.el)}

  }
function resetParticles(){const right=volumeToX(state.volume)-15;state.particles.forEach((p,i)=>{p.x=INNER_LEFT+16+random()*Math.max(35,right-INNER_LEFT-28);p.y=TOP+16+random()*(BOTTOM-TOP-32);const a=(i*137.5%360)*Math.PI/180;p.vx=Math.cos(a)*74;p.vy=Math.sin(a)*74})}
function renderForces(p){const host=$('forceLayer');host.innerHTML='';const x=volumeToX(state.volume)-18,count=clamp(Math.round((p-60)/30)+2,2,10),len=18+((p-MIN_P)/(MAX_P-MIN_P))*36;for(let i=0;i<count;i++){const y=128+i*(150/(Math.max(1,count-1)));host.append(svg('line',{x1:x-len,y1:y,x2:x-4,y2:y,class:'force-arrow-soft'}));host.append(svg('line',{x1:x-len,y1:y,x2:x-4,y2:y,class:'force-arrow','marker-end':'url(#home-gas-forceHead)'}))}}
function renderGraph(p){const baseV=state.free?state.freeStartV:c().startV,gx=graphX(state.volume),gy=graphY(p),sx=graphX(baseV),sy=graphY(pressure(baseV));setAttrs($('graphCurrent'),{cx:gx,cy:gy});setAttrs($('graphStart'),{cx:sx,cy:sy});const label=$('graphPointLabel');label.textContent=`(${fmt(state.volume,2)} L, ${fmt(p,0)} kPa)`;setAttrs(label,{x:clamp(gx+10,GRAPH.x+6,GRAPH.x+GRAPH.w-105),y:clamp(gy-9,GRAPH.y+11,GRAPH.y+GRAPH.h-5)});let d='';state.trace.forEach(v=>{const x=graphX(v),y=graphY(pressure(v));d+=`${d?'L':'M'}${x.toFixed(1)} ${y.toFixed(1)} `});$('graphTrace').setAttribute('d',d);const pins=$('graphPins');pins.innerHTML='';state.pins.forEach((q,i)=>{pins.append(svg('circle',{cx:graphX(q.v),cy:graphY(q.p),r:5,class:'graph-pin'}));const t=svg('text',{x:graphX(q.v)+7,y:graphY(q.p)+12,fill:'#634a88','font-size':'7','font-weight':'800'});t.textContent=i+1;pins.append(t)})}
function renderGauge(p){const a=gaugeAngle(p),q=polar(GAUGE.cx,GAUGE.cy,72,a);setAttrs($('gaugeNeedle'),{x2:q.x,y2:q.y});$('gaugeValue').textContent=`${fmt(p,0)} kPa`}
function renderImpactPanel(rate){const pulses=[...$('impactPulses').children],n=clamp(Math.round(rate/2),4,pulses.length),phase=Math.floor(state.pulsePhase)%pulses.length;pulses.forEach((el,i)=>el.classList.toggle('on',((i-phase+pulses.length)%pulses.length)<n));$('impactValue').textContent=`${fmt(rate,0)} model impacts/s`;const baseV=state.free?state.freeStartV:c().startV,ratio=rate/impactRate(baseV);$('impactExplanation').textContent=ratio>1.02?'shorter journey to the piston → impacts happen more often':ratio<.98?'longer journey to the piston → impacts happen less often':'same journey length → same impact rate';const unlocked=state.solved[0]&&state.solved[1]||state.caseIndex>=2||state.free;$('productValue').textContent=unlocked?`${fmt(K,0)} kPa·L`:'revealed after two tests';$('productBox').setAttribute('fill',unlocked?'#eef3fa':'#f4f7fb')}
function renderAll(){const p=pressure(state.volume),rate=impactRate(state.volume),px=volumeToX(state.volume);$('gasChamber').setAttribute('width',px-INNER_LEFT);setAttrs($('gasClipRect'),{width:Math.max(1,px-INNER_LEFT-1)});$('piston').setAttribute('transform',`translate(${px} 0)`);$('piston').setAttribute('aria-valuenow',fmt(state.volume,2));$('piston').setAttribute('aria-valuetext',`${fmt(state.volume,2)} litres, pressure ${fmt(p,0)} kilopascals`);renderGauge(p);renderForces(p);renderGraph(p);renderImpactPanel(rate);}
function animation(now){const dt=Math.min(.035,(now-state.lastTime)/1000);state.lastTime=now;state.pulsePhase+=dt*8;const right=volumeToX(state.volume)-15;for(const p of state.particles){p.x+=p.vx*dt;p.y+=p.vy*dt;if(p.x<INNER_LEFT+7){p.x=INNER_LEFT+7;p.vx=Math.abs(p.vx)}if(p.x>right){p.x=right;p.vx=-Math.abs(p.vx);state.flashes.push({x:right+1,y:p.y,life:1})}if(p.y<TOP+7){p.y=TOP+7;p.vy=Math.abs(p.vy)}if(p.y>BOTTOM-7){p.y=BOTTOM-7;p.vy=-Math.abs(p.vy)}p.el.setAttribute('cx',p.x);p.el.setAttribute('cy',p.y)}
    const host=$('collisionLayer');host.innerHTML='';state.flashes=state.flashes.filter(f=>{f.life-=dt*3.2;if(f.life<=0)return false;const g=svg('g',{transform:`translate(${f.x} ${f.y})`,opacity:f.life});g.append(svg('line',{x1:-11,y1:0,x2:-2,y2:0,class:'collision-flash live'}));g.append(svg('line',{x1:-8,y1:-8,x2:-2,y2:-2,class:'collision-flash live'}));g.append(svg('line',{x1:-8,y1:8,x2:-2,y2:2,class:'collision-flash live'}));host.append(g);return true});
    if(Math.floor(state.pulsePhase*2)%2===0)renderImpactPanel(impactRate(state.volume));}
$('stage').style.setProperty('--lab-chart-text-size','11px');
initStatic();let simulated=0;
function resetPreview(){state.volume=6;state.trace=[6];state.flashes=[];state.lastTime=0;state.pulsePhase=0;seed=42;resetParticles();simulated=0;renderAll();animation(0);}
resetPreview();
// Replay the lab's 6 L to 3 L compression with its original particle collisions,
// pressure law, forces, gauge, and graph. Fixed steps make pause/seek deterministic.
return time=>{
  if(time<simulated)resetPreview();
  while(simulated+1000/60<=time){simulated+=1000/60;state.volume=Math.round((6-3*clamp((simulated-500)/6000,0,1))*100)/100;
    if(state.trace.at(-1)!==state.volume){state.trace.push(state.volume);if(state.trace.length>180)state.trace.shift();}
    renderAll();animation(simulated);
  }
};

})();
let lastTime;
return time=>{if(time===lastTime)return;lastTime=time;root.host.style.setProperty('--preview-animation-time',String(time));update(time);};
}
