// Generated by scripts/sync-home-previews.mjs from labs-src/computer-science/dijkstra-a-star-graph-search/lab.html.
// Source rendering functions are preserved; only UI orchestration outside the excerpt is omitted.
export function mount(root) {
const update=(()=>{
const $ = id => root.getElementById('home-graph-' + id);

const nodeIds=["S","A","B","C","D","E","F","G"];
  const positions={S:[70,215],A:[190,95],B:[190,325],C:[345,70],D:[360,220],E:[500,335],F:[530,120],G:[690,215]};
  const heuristic={S:8,A:7,B:6,C:6,D:4,E:4,F:2,G:0};
  const baseEdges=[["S","A",2],["S","B",2],["A","C",2],["A","D",5],["B","D",2],["B","E",4],["C","F",5],["D","F",2],["D","E",2],["E","G",4],["F","G",2]];
  const labels={dijkstra:"Dijkstra",astar:"A*"};
  
const graphNodes=[...root.querySelectorAll('.node[data-node]')],graphEdges=[...root.querySelectorAll('.edge[data-edge]')],graphWeights=[...root.querySelectorAll('.edge-weight')];
const edgeCosts=Object.fromEntries(baseEdges.map(([a,b,w])=>[edgeKey(a,b),w])),edgeNames=Object.fromEntries(baseEdges.map(([a,b])=>[edgeKey(a,b),a+'–'+b]));
const costEditingUnlocked=false,selectedCostEdge=null,previousExperiment=null,revealMinimum=false,busy=false;
let search,inspected=null,activeEdge=null,activeNeighbour=null,scannedEdges=new Set();
function edgeKey(a,b){return[a,b].sort().join("|")}
function currentEdges(){return baseEdges.map(([a,b])=>[a,b,edgeCosts[edgeKey(a,b)]])}
function neighbours(id){return currentEdges().filter(([a,b])=>a===id||b===id).map(([a,b,w])=>({id:a===id?b:a,weight:w,edge:edgeKey(a,b)}))}
function priority(id){if(!search)return Infinity;return search.distances[id]+(search.algorithm==="astar"?heuristic[id]:0)}
function frontierNodes(){return search?nodeIds.filter(id=>search.frontier.has(id)):[]}
function minimumCandidates(){const ids=frontierNodes();if(!ids.length)return[];const min=Math.min(...ids.map(priority));return ids.filter(id=>priority(id)===min)}
function createSearch(algorithm){const distances=Object.fromEntries(nodeIds.map(id=>[id,Infinity]));distances.S=0;return{algorithm,distances,previous:{},frontier:new Set(["S"]),settled:[],current:null,route:[],complete:false,tieChoices:[],lastReason:"S starts with travelled cost g = 0."}}
function buildRoute(){const route=[];let current="G";while(current){route.unshift(current);current=search.previous[current]}return route}
function previousRouteEdges(){if(!previousExperiment)return new Set();const edges=new Set();Object.values(previousExperiment.results).filter(Boolean).forEach(result=>result.route.slice(1).forEach((id,i)=>edges.add(edgeKey(result.route[i],id))));return edges}
function renderGraph(){
    const frontier=new Set(search?.frontier||[]),settled=new Set(search?.settled||[]),routeNodes=new Set(search?.route||[]),minima=new Set(revealMinimum?minimumCandidates():[]);
    const routeEdges=new Set((search?.route||[]).slice(1).map((id,i)=>edgeKey(search.route[i],id)));const previousEdges=previousRouteEdges();
    graphNodes.forEach(node=>{const id=node.dataset.node;const discovered=Number.isFinite(search?.distances[id]);node.classList.toggle("is-frontier",frontier.has(id));node.classList.toggle("is-settled",settled.has(id));node.classList.toggle("is-current",search?.current===id&&!search?.complete);node.classList.toggle("is-route",routeNodes.has(id));node.classList.toggle("is-inspected",inspected===id);node.classList.toggle("is-relax-target",activeNeighbour===id);node.classList.toggle("is-minimum",minima.has(id));node.setAttribute("role",frontier.has(id)?"button":"img");node.setAttribute("tabindex",frontier.has(id)&&!busy?"0":"-1");
      const metric=node.querySelector(".node-metric");metric.textContent=discovered?(search.algorithm==="astar"?`g ${search.distances[id]} · h ${heuristic[id]} · f ${priority(id)}`:`g ${search.distances[id]}`):(id==="S"?"start":id==="G"?"goal":"");
      node.setAttribute("aria-label",frontier.has(id)?`${id}, frontier. ${search.algorithm==="astar"?`g ${search.distances[id]}, h ${heuristic[id]}, priority ${priority(id)}`:`g and priority ${search.distances[id]}`}`:`${id}. ${metric.textContent}`);
    });
    graphEdges.forEach(edge=>{edge.classList.toggle("previous-route",previousEdges.has(edge.dataset.edge));edge.classList.toggle("route-edge",routeEdges.has(edge.dataset.edge));edge.classList.toggle("scanned-edge",scannedEdges.has(edge.dataset.edge));edge.classList.toggle("active-relax",activeEdge===edge.dataset.edge)});
    graphWeights.forEach(weight=>{const key=weight.closest(".edge").dataset.edge;weight.querySelector("text").textContent=edgeCosts[key];weight.classList.toggle("editable",costEditingUnlocked);weight.classList.toggle("selected",selectedCostEdge===key);weight.setAttribute("role",costEditingUnlocked?"button":"img");weight.setAttribute("tabindex",costEditingUnlocked&&!busy?"0":"-1");weight.setAttribute("aria-label",costEditingUnlocked?`${edgeNames[key]} road cost ${edgeCosts[key]}. Select to adjust.`:`${edgeNames[key]} road cost ${edgeCosts[key]}.`)});
    const line=$("heuristic-line"),label=$("heuristic-label");const show=Boolean(inspected&&search?.algorithm==="astar");line.toggleAttribute("hidden",!show);label.toggleAttribute("hidden",!show);if(show){const[x,y]=positions[inspected];line.setAttribute("x1",x);line.setAttribute("y1",y);label.setAttribute("x",(x+690)/2);label.setAttribute("y",(y+215)/2-7);label.textContent=`h = ${heuristic[inspected]}`}
    const frontierText=frontier.size?[...frontier].join(", "):"none",settledText=settled.size?[...settled].join(", "):"none";const costs=baseEdges.map(([a,b])=>`${a}–${b} ${edgeCosts[edgeKey(a,b)]}`).join(", ");$("graph-description").textContent=`${labels[search?.algorithm]||"No search"}. Settled: ${settledText}. Frontier: ${frontierText}. Road costs: ${costs}.`;
  }
// settleAndRelax's source state transitions, scheduled on the shared preview clock.
function* steps(){
  while(!search.complete){const id=minimumCandidates()[0];if(!id)return;
    inspected=id;activeEdge=null;activeNeighbour=null;scannedEdges=new Set();search.frontier.delete(id);search.settled.push(id);search.current=id;yield 450;inspected=null;
    if(id==='G'){search.route=buildRoute();search.complete=true;return;}
    for(const item of neighbours(id).filter(({id:n})=>!search.settled.includes(n))){activeEdge=item.edge;activeNeighbour=item.id;scannedEdges.add(item.edge);const old=search.distances[item.id],proposed=search.distances[id]+item.weight;yield 560;if(proposed<old){search.distances[item.id]=proposed;search.previous[item.id]=id;search.frontier.add(item.id);yield 360;}}
    activeEdge=null;activeNeighbour=null;search.current=null;yield 450;
  }
}
let iterator,nextAt,last=0;
function reset(){search=createSearch('astar');inspected=null;activeEdge=null;activeNeighbour=null;scannedEdges=new Set();iterator=steps();nextAt=1000;renderGraph();}
reset();return time=>{if(time<last)reset();last=time;while(time>=nextAt){const step=iterator.next();renderGraph();if(step.done){nextAt=Infinity;break;}nextAt+=step.value;}};

})();
let lastTime;
return time=>{if(time===lastTime)return;lastTime=time;root.host.style.setProperty('--preview-animation-time',String(time));update(time);};
}
