// Generated by scripts/sync-home-previews.mjs from labs-src/computer-science/packet-switching/lab.html.
// Source rendering functions are preserved; only UI orchestration outside the excerpt is omitted.
export function mount(root) {
const update=(()=>{
const $ = id => root.getElementById('home-packet-' + id);

const defaultNodes=[
    {id:"A",type:"endpoint",label:"NIC A",x:8,y:48,fixed:true},
    {id:"B",type:"endpoint",label:"NIC B",x:92,y:52,fixed:true},
    {id:"R1",type:"router",label:"Router 1",x:20,y:43},
    {id:"R2",type:"router",label:"Router 2",x:43,y:17},
    {id:"R3",type:"router",label:"Router 3",x:50,y:49},
    {id:"R4",type:"router",label:"Router 4",x:31,y:78},
    {id:"R5",type:"router",label:"Router 5",x:77,y:72}
  ];

  const defaultEdges=[
    ["A","R1"],["R1","R2"],["R1","R3"],["R1","R4"],
    ["R2","R3"],["R2","R5"],["R2","B"],
    ["R3","R4"],["R3","R5"],["R4","R5"],["R5","B"]
  ];


const nodes=new Map(defaultNodes.map(n=>[n.id,{...n}])),edges=new Set(defaultEdges.map(([a,b])=>edgeKey(a,b)));
const routerRuntime=new Map(),edgeTraffic=new Map(),tool='move',connectSource=null;
function edgeKey(a,b){return [a,b].sort().join("|")}
function edgeNodes(key){return key.split("|")}
function nodePosition(id){
    const node=nodes.get(id);
    const canvas=$("networkCanvas");
    return {
      x:node.x/100*canvas.clientWidth,
      y:node.y/100*canvas.clientHeight
    };
  }
function routerRuntimeFor(id){
    if(!routerRuntime.has(id)){
      routerRuntime.set(id,{current:null,queue:0,phase:"idle",colour:"#7a8790",tail:Promise.resolve()});
    }
    return routerRuntime.get(id);
  }
function routerArtwork(id,queue,status,active=false){        return `
          <div class="router-top">
            <span class="router-name">${id}</span>
            <span class="router-queue">${queue}</span>
          </div>
          <div class="router-body">
            <div class="router-ports">
              <i class="router-port"></i><i class="router-port"></i><i class="router-port"></i><i class="router-port"></i><i class="router-port"></i>
            </div>
            <div class="router-leds">
              <i class="router-led power"></i>
              <i class="router-led activity ${active?"on":""}"></i>
              <i class="router-led queue ${queue>0?"on":""}"></i>
            </div>
          </div>
          <div class="router-status">${status}</div>`;}
function updateRouterVisual(id){
    const node=$("nodeLayer").querySelector(`[data-id="${id}"]`);
    if(!node) return;
    const runtime=routerRuntimeFor(id);
    node.style.setProperty("--packet-color",runtime.colour);
    node.classList.toggle("processing",runtime.phase==="processing");
    node.classList.toggle("forwarding",runtime.phase==="forwarding");
    node.classList.toggle("waiting",!runtime.current&&runtime.queue>0);
    const queue=node.querySelector(".router-queue");
    if(queue) queue.textContent=runtime.queue;
    const status=node.querySelector(".router-status");
    if(status){
      status.textContent=runtime.phase==="processing"
        ? `PROCESS ${runtime.current?.id||""}`
        : runtime.phase==="forwarding"
          ? `FORWARD ${runtime.current?.id||""}`
          : runtime.queue>0
            ? "WAITING"
            : "IDLE";
    }
    const activity=node.querySelector(".router-led.activity");
    const waiting=node.querySelector(".router-led.queue");
    activity?.classList.toggle("on",Boolean(runtime.current));
    waiting?.classList.toggle("on",runtime.queue>0);
  }
function setEdgeVisual(key,active,colour){
    const line=$("networkSvg").querySelector(`.link[data-key="${key}"]`);
    if(!line) return;
    line.classList.toggle("active",active);
    if(colour) line.style.setProperty("--packet-color",colour);
  }
function packetColour(index,total){
    const hue=(index*57 + total*13)%360;
    return `hsl(${hue} 68% 50%)`;
  }
function renderEdges(){
    const svg=$("networkSvg");
    svg.innerHTML="";
    const width=$("networkCanvas").clientWidth;
    const height=$("networkCanvas").clientHeight;
    svg.setAttribute("viewBox",`0 0 ${width} ${height}`);

    [...edges].sort().forEach(key=>{
      const [a,b]=edgeNodes(key);
      const p1=nodePosition(a);
      const p2=nodePosition(b);
      const group=document.createElementNS("http://www.w3.org/2000/svg","g");

      const hit=document.createElementNS("http://www.w3.org/2000/svg","line");
      hit.setAttribute("x1",p1.x);hit.setAttribute("y1",p1.y);
      hit.setAttribute("x2",p2.x);hit.setAttribute("y2",p2.y);
      hit.setAttribute("class","link-hit");
      hit.dataset.key=key;


      const line=document.createElementNS("http://www.w3.org/2000/svg","line");
      line.setAttribute("x1",p1.x);line.setAttribute("y1",p1.y);
      line.setAttribute("x2",p2.x);line.setAttribute("y2",p2.y);
      line.setAttribute("class","link");
      line.dataset.key=key;

      group.append(hit,line);
      svg.appendChild(group);
    });

    edgeTraffic.forEach((traffic,key)=>{
      if(traffic.count>0) setEdgeVisual(key,true,traffic.colour);
    });
  }
function renderNodes(){
    const layer=$("nodeLayer");
    layer.innerHTML="";

    nodes.forEach(node=>{
      const element=document.createElement("div");
      element.className=`network-node ${node.type==="router"?"router-node":"endpoint-node"}`;
      element.dataset.id=node.id;
      element.style.left=`${node.x}%`;
      element.style.top=`${node.y}%`;
      element.tabIndex=-1;
      element.setAttribute("role","button");
      const action=tool==="connect"?"Select to connect":tool==="remove"?"Select to remove":node.type==="router"?"Drag or use the arrow keys to move":"Network endpoint";
      element.setAttribute("aria-label",`${node.id}. ${action}.`);
      if(tool==="move"&&node.type==="router") element.setAttribute("aria-keyshortcuts","ArrowLeft ArrowRight ArrowUp ArrowDown");

      if(node.id===connectSource) element.classList.add("selected");

      if(node.type==="endpoint"){
        element.innerHTML=`${node.id}<small>${node.label}</small>`;
      }else{
        const runtime=routerRuntimeFor(node.id);
        element.style.setProperty("--packet-color",runtime.colour);
        element.classList.toggle("processing",runtime.phase==="processing");
        element.classList.toggle("forwarding",runtime.phase==="forwarding");
        element.classList.toggle("waiting",!runtime.current&&runtime.queue>0);

        const status=runtime.phase==="processing"
          ? `PROCESS ${runtime.current?.id||""}`
          : runtime.phase==="forwarding"
            ? `FORWARD ${runtime.current?.id||""}`
            : runtime.queue>0
              ? "WAITING"
              : "IDLE";

        element.innerHTML=routerArtwork(node.id,runtime.queue,status,!!runtime.current);
      }

      layer.appendChild(element);
});
}
renderEdges();renderNodes();
// Valid routes on the source topology. Source link, queue, processing, and forwarding
// durations are scheduled here on the shared clock instead of independent async loops.
const routes=[['A','R1','R2','B'],['A','R1','R3','R5','B'],['A','R1','R4','R5','B']];
const packets=Array.from({length:6},(_,index)=>({id:'P'+(index+1),index,colour:packetColour(index,6),route:routes[index%3],links:[],stops:[]}));
const pending=packets.map(packet=>({time:packet.index*220,packet,hop:0})),available=new Map();
while(pending.length){
  pending.sort((a,b)=>a.time-b.time);const {time,packet,hop}=pending.shift();
  const from=packet.route[hop],to=packet.route[hop+1],end=time+820+((packet.index*43+hop*31)%3)*130;
  packet.links.push({from,to,start:time,end});
  if(nodes.get(to).type==='router'){
    const start=Math.max(end,available.get(to)||0),numeric=Number(to.replace(/\D/g,''))||1;
    const processed=start+500+((packet.index*37+numeric*29)%3)*110,forwarded=processed+210;
    packet.stops.push({id:to,arrival:end,start,processed,end:forwarded});available.set(to,forwarded);
    pending.push({time:forwarded,packet,hop:hop+1});
  }
}
for(const packet of packets){const dot=document.createElement('div');dot.className='packet-dot lab-packet-marker';dot.style.setProperty('--packet',packet.colour);dot.innerHTML='<span>'+packet.id+'</span>';$('packetLayer').append(dot);packet.dot=dot;}
return time=>{
  const now=time+1500; // Enter during transmission, with packets already reaching R1.
  for(const key of edges)setEdgeVisual(key,false);
  for(const id of nodes.keys())if(nodes.get(id).type==='router'){
    const runtime=routerRuntimeFor(id);runtime.current=null;runtime.phase='idle';runtime.queue=0;
    for(const packet of packets)for(const stop of packet.stops)if(stop.id===id){
      if(now>=stop.arrival&&now<stop.start)runtime.queue++;
      if(now>=stop.start&&now<stop.end){runtime.current=packet;runtime.colour=packet.colour;runtime.phase=now<stop.processed?'processing':'forwarding';}
    }
    updateRouterVisual(id);
  }
  for(const packet of packets){
    const link=packet.links.find(l=>now>=l.start&&now<l.end);
    const stop=packet.stops.find(s=>now>=s.arrival&&now<s.end);
    packet.dot.hidden=!link&&!stop;
    if(link){
      const from=nodePosition(link.from),to=nodePosition(link.to),t=(now-link.start)/(link.end-link.start);
      const eased=t<.5?2*t*t:1-Math.pow(-2*t+2,2)/2;
      packet.dot.style.transform='translate('+(from.x+(to.x-from.x)*eased)+'px,'+(from.y+(to.y-from.y)*eased)+'px)';
      setEdgeVisual(edgeKey(link.from,link.to),true,packet.colour);
    }else if(stop){const p=nodePosition(stop.id);packet.dot.style.transform='translate('+p.x+'px,'+p.y+'px)';}
  }
};

})();
let lastTime;
return time=>{if(time===lastTime)return;lastTime=time;root.host.style.setProperty('--preview-animation-time',String(time));update(time);};
}
