// Generated by scripts/sync-home-previews.mjs from labs-src/mathematics/sequence-patterns-differences/lab.html.
// Source rendering functions are preserved; only UI orchestration outside the excerpt is omitted.
export function mount(root) {
const update=(()=>{
const $ = id => root.getElementById('home-patterns-' + id);

const GRID_COLS=12,GRID_ROWS=7,MAX_TILES=16;
const key=(x,y)=>`${x},${y}`,parseKey=k=>k.split(',').map(Number),diffSet=(a,b)=>new Set([...b].filter(v=>!a.has(v)));
const family=()=>({id:'quadratic',shape:squareShape,maxStage:4});
const state={currentStage:2,placed:new Map(),notice:null};
const bindTile=()=>{};
// Ported cells are inert; original interaction handlers are not installed.
function bounds(set){const arr=[...set].map(parseKey);if(!arr.length)return{minX:0,minY:0,maxX:0,maxY:0,w:1,h:1};const xs=arr.map(v=>v[0]),ys=arr.map(v=>v[1]);const minX=Math.min(...xs),maxX=Math.max(...xs),minY=Math.min(...ys),maxY=Math.max(...ys);return{minX,minY,maxX,maxY,w:maxX-minX+1,h:maxY-minY+1}}
function squareShape(n){const s=new Set();for(let x=0;x<n;x++)for(let y=0;y<n;y++)s.add(key(x,y));return s}
function makeRefGrid(shape,lastGrowth=new Set(),demo=false){const b=bounds(shape),holder=document.createElement('div');holder.className='ref-grid';holder.style.width=`calc(${b.w} * var(--cell))`;holder.style.height=`calc(${b.h} * var(--cell))`;for(const k of shape){const[x,y]=parseKey(k),d=document.createElement('div');d.className='ref-tile'+(lastGrowth.has(k)?' last-growth':'')+(demo&&lastGrowth.has(k)?' demo-in':'');d.style.left=`calc(${x-b.minX} * var(--cell))`;d.style.top=`calc(${y-b.minY} * var(--cell))`;holder.appendChild(d)}return holder}
function renderReference(demo=false){const f=family(),box=$('referenceStage');box.innerHTML='';$('referenceCaption').textContent='';if(f.id==='ambiguity'){box.appendChild(makeRefGrid(state.refShape));$('referenceValue').textContent='Stage 3 · 6 squares';return}const shape=f.shape(state.currentStage),prev=state.currentStage>1?f.shape(state.currentStage-1):new Set(),growth=diffSet(prev,shape);box.appendChild(makeRefGrid(shape,growth,demo));$('referenceValue').textContent=`Stage ${state.currentStage} · ${shape.size} squares`}
function maxShapeForFamily(f){return f.shape(f.maxStage)}
function buildAnchorFor(shape){const b=bounds(shape);return{x:Math.floor((GRID_COLS-b.w)/2)-b.minX,y:Math.floor((GRID_ROWS-b.h)/2)-b.minY}}
function buildKeyFromModel(k){const a=buildAnchorFor(maxShapeForFamily(family())),[x,y]=parseKey(k);return key(x+a.x,y+a.y)}
function renderGrid(){const grid=$('buildGrid');grid.innerHTML='';for(let y=0;y<GRID_ROWS;y++)for(let x=0;x<GRID_COLS;x++){const c=document.createElement('button');c.type='button';c.className='grid-cell';c.dataset.cell=key(x,y);c.tabIndex=-1;c.setAttribute('aria-label',`Lattice cell column ${x+1}, row ${y+1}`);grid.appendChild(c)}}
function targetGrowthSet(){const f=family();if(f.id==='ambiguity')return null;const cur=f.shape(state.currentStage),next=f.shape(state.currentStage+1);return new Set([...diffSet(cur,next)].map(buildKeyFromModel))}
function ghostSet(){const f=family();if(f.id==='ambiguity'){const b=bounds(state.refShape),a={x:Math.floor((GRID_COLS-b.w)/2)-b.minX,y:Math.floor((GRID_ROWS-b.h)/2)-b.minY};return new Set([...state.refShape].map(k=>{const[x,y]=parseKey(k);return key(x+a.x,y+a.y)}))}return new Set([...f.shape(state.currentStage)].map(buildKeyFromModel))}
function renderBuild(){const f=family(),shell=$('buildStageShell');shell.innerHTML='';const ghosts=ghostSet();if(ghosts.size){const gb=bounds(ghosts),lab=document.createElement('span');lab.className='previous-pattern-label';lab.textContent='previous pattern';lab.style.left=`calc(50% - ${GRID_COLS/2} * var(--cell) + ${gb.minX} * var(--cell))`;lab.style.top=`calc(50% - ${GRID_ROWS/2} * var(--cell) + ${gb.minY} * var(--cell) - 18px)`;shell.appendChild(lab)}for(const k of ghosts){const[x,y]=parseKey(k),d=document.createElement('div');d.className='build-ghost';d.style.left=`calc(50% - ${GRID_COLS/2} * var(--cell) + ${x} * var(--cell))`;d.style.top=`calc(50% - ${GRID_ROWS/2} * var(--cell) + ${y} * var(--cell))`;shell.appendChild(d)}for(const[cell,tileId]of state.placed){const[x,y]=parseKey(cell),d=document.createElement('button');d.type='button';d.className='placed-tile';d.dataset.tileId=tileId;d.dataset.cell=cell;d.setAttribute('aria-label','Placed square. Drag back to the loose material area to remove it.');d.style.left=`calc(50% - ${GRID_COLS/2} * var(--cell) + ${x} * var(--cell))`;d.style.top=`calc(50% - ${GRID_ROWS/2} * var(--cell) + ${y} * var(--cell))`;bindTile(d,'placed');shell.appendChild(d)}if(f.id==='ambiguity'){$('buildValue').textContent=state.futures.length===0?'Future A':state.futures.length===1?'Future B':'Compared';$('dropMessage').textContent=''}else{$('buildValue').textContent=state.currentStage<f.maxStage?`Build Stage ${state.currentStage+1}`:'Pattern built';$('dropMessage').textContent=''}}
function renderTray(){const used=new Set(state.placed.values()),field=$('looseField');field.innerHTML='';for(let i=1;i<=MAX_TILES;i++){const id=`tile-${i}`,b=document.createElement('button');b.type='button';b.className='loose-tile'+(used.has(id)?' used':'');b.dataset.tileId=id;b.setAttribute('aria-label',`Loose square ${i}`);bindTile(b,'loose');field.appendChild(b)}}
function validTargetCell(k){const f=family();return f.id==='ambiguity'?validAmbiguityCell(k):targetGrowthSet().has(k)&&!state.placed.has(k)}
let count=0,finished=false,referenceMotion=[];
renderReference();renderGrid();renderBuild();renderTray();
const targets=[...targetGrowthSet()];
return time=>{
  const target=Math.min(targets.length,Math.max(0,Math.floor((time-1400)/1400)+1));
  if(target<count){referenceMotion.forEach(a=>a.cancel());referenceMotion=[];state.currentStage=2;state.placed.clear();count=0;finished=false;renderReference();renderBuild();renderTray();}
  if(target!==count){while(count<target){const cell=targets[count];if(!validTargetCell(cell))throw new Error('Invalid preview tile placement');state.placed.set(cell,'tile-'+(count+1));state.notice=null;count++;}renderBuild();renderTray();}
  // completeStage's original 420ms snap and 450ms transfer, on the shared pauseable clock.
  if(count===targets.length&&!finished){
    $('dropMessage').className='drop-message good';$('dropMessage').innerHTML='<strong>Stage 3 complete.</strong> You added 5 squares.';
    root.querySelectorAll('.placed-tile').forEach(n=>{n.classList.add('snap');n.style.setProperty('--preview-animation-time',String(time-7000));});
    if(time>=7420){
      const reference=$('referenceStage').querySelector('.ref-grid');
      if(!referenceMotion.length){referenceMotion=[reference.animate([{transform:'none'},{transform:'translateX(-32px) scale(.92)'}],{duration:450,easing:'cubic-bezier(.2,.75,.2,1)',fill:'forwards'}),reference.animate([{opacity:1},{opacity:0}],{duration:250,easing:'ease',fill:'forwards'})];referenceMotion.forEach(a=>a.pause());}
      referenceMotion.forEach(a=>a.currentTime=time-7420);
      $('buildStageShell').classList.add('fly-left');$('buildStageShell').style.setProperty('--preview-animation-time',String(time-7420));
    }
    if(time>=7870){state.currentStage=3;state.placed.clear();$('buildStageShell').classList.remove('fly-left');renderReference(true);renderBuild();renderTray();finished=true;}
  }
};

})();
let lastTime;
return time=>{if(time===lastTime)return;lastTime=time;root.host.style.setProperty('--preview-animation-time',String(time));update(time);};
}
