// Generated by scripts/sync-home-previews.mjs from labs-src/mathematics/trigonometric-function-periodicity-solutions/lab.html.
// Source rendering functions are preserved; only UI orchestration outside the excerpt is omitted.
export function mount(root) {
const update=(()=>{
const $ = id => root.getElementById('home-trig-' + id);

const DEG=Math.PI/180,cases=[{id:'sine',tag:'Sine symmetry',fn:'sin',kind:'solve',target:Math.sqrt(3)/2,targetText:'√3/2',equation:'sin x = √3/2',mission:'Find every angle from 0° to 360° where sin x = √3/2.',relation:'180° − α',partner:120,completion:'The graph and working give x = 60° and 120°.'}];
const state={caseIndex:0,angle:0,visited:new Uint8Array(360),discovered:new Set(),complete:false,fullTurns:0};
let graphSize={w:479,h:310},lastAngle=0;
function mod(n,m){return((n%m)+m)%m}
function normAngle(a){let n=mod(a,360);if(Math.abs(n-360)<1e-9)n=0;return n}
function trig(fn,a){const r=a*DEG;if(fn==='sin')return Math.sin(r);if(fn==='cos')return Math.cos(r);const c=Math.cos(r);if(Math.abs(c)<1e-9)return NaN;return Math.tan(r)}
function fmt(n,d=1){if(!Number.isFinite(n))return'undefined';const z=Math.abs(n)<.0000001?0:n;return z.toFixed(d).replace(/\.0$/,'')}
function fmtValue(n){if(!Number.isFinite(n))return'undefined';if(Math.abs(n)>=100)return fmt(n,1);return fmt(n,3)}
function currentCase(){return cases[state.caseIndex]}
function dedupeSolutions(arr){
  const out=[];for(const x of arr.sort((a,b)=>a-b)){if(!out.some(y=>Math.abs(y-x)<1e-6))out.push(x)}return out;
}
function solutions(c){
  const k=c.target,eps=1e-9,out=[];
  if(c.fn==='sin'){
    if(Math.abs(k)>1+eps)return[];
    if(Math.abs(k-1)<eps)return[90];if(Math.abs(k+1)<eps)return[270];
    if(Math.abs(k)<eps)return[0,180,360];
    const a=Math.asin(k)/DEG;out.push(mod(a,360),mod(180-a,360));
  }else if(c.fn==='cos'){
    if(Math.abs(k)>1+eps)return[];
    if(Math.abs(k-1)<eps)return[0,360];if(Math.abs(k+1)<eps)return[180];
    const a=Math.acos(k)/DEG;out.push(a,360-a);
  }else{
    const a=Math.atan(k)/DEG;for(let n=-3;n<=3;n++){const x=a+180*n;if(x>=-eps&&x<=360+eps)out.push(Math.abs(x)<eps?0:Math.abs(x-360)<eps?360:x)}
  }
  return dedupeSolutions(out);
}
function isVisitedNear(angle,tol=2){
  if(angle===360)return state.visited[0]&&state.complete;
  const a=normAngle(angle);for(let d=-tol;d<=tol;d++){if(state.visited[mod(Math.round(a)+d,360)])return true}return false;
}
function updateDiscoveries(){for(const s of solutions(currentCase()))if(isVisitedNear(s))state.discovered.add(String(s))}
function markUnwrappedSegment(a,b){
  const delta=b-a,steps=Math.max(1,Math.ceil(Math.abs(delta)*2));
  for(let i=0;i<=steps;i++){
    const u=a+delta*i/steps,n=normAngle(u),bin=mod(Math.round(n),360);state.visited[bin]=1;
  }
  const beforeTurn=Math.floor(a/360),afterTurn=Math.floor(b/360);if(beforeTurn!==afterTurn)state.fullTurns+=Math.abs(afterTurn-beforeTurn);
  const visitedCount=state.visited.reduce((s,v)=>s+v,0);if(visitedCount>=354){state.complete=true;for(let i=0;i<360;i++)state.visited[i]=1}
  updateDiscoveries();
}
function svgEl(name,attrs={},text=''){const a=Object.entries(attrs).map(([k,v])=>`${k}="${String(v).replace(/&/g,'&amp;').replace(/"/g,'&quot;')}"`).join(' ');return `<${name}${a?' '+a:''}>${text}</${name}>`}
function graphYRange(c){return c.fn==='tan'?[-4.6,4.6]:[-1.4,1.4]}
function graphMap(w,h,c){const L=40,R=18,T=9,B=29,[yMin,yMax]=graphYRange(c);return{L,R,T,B,W:w-L-R,H:h-T-B,yMin,yMax,x:x=>L+(x/360)*(w-L-R),y:y=>T+(yMax-y)/(yMax-yMin)*(h-T-B)}}
function tracePaths(map,c){
  let segs=[],current=[];const flush=()=>{if(current.length>1)segs.push(current);current=[]};
  for(let i=0;i<=360;i++){
    const seen=i===360?state.visited[0]:state.visited[i];if(!seen){flush();continue}
    const v=trig(c.fn,i);if(!Number.isFinite(v)){flush();continue}
    if(c.fn==='tan'&&Math.abs(v)>map.yMax*1.08){flush();continue}
    current.push([map.x(i),map.y(v)]);
  }flush();return segs.map(points=>'M '+points.map(p=>`${p[0].toFixed(2)} ${p[1].toFixed(2)}`).join(' L '));
}
function renderGraph(){
  const svg=$('graphSvg'),w=Math.max(300,svg.clientWidth||graphSize.w),h=Math.max(230,svg.clientHeight||graphSize.h);graphSize={w,h};const c=currentCase(),m=graphMap(w,h,c);let s='';
  s+=svgEl('rect',{x:m.L,y:m.T,width:m.W,height:m.H,rx:8,fill:'#fff',stroke:'none'});
  if(c.fn!=='tan'){
    const y1=m.y(1),ym1=m.y(-1);s+=svgEl('rect',{x:m.L,y:y1,width:m.W,height:ym1-y1,class:'svg-range'});s+=svgEl('line',{x1:m.L,y1:y1,x2:m.L+m.W,y2:y1,class:'svg-range-edge'});s+=svgEl('line',{x1:m.L,y1:ym1,x2:m.L+m.W,y2:ym1,class:'svg-range-edge'});
  }
  for(const x of [0,90,180,270,360]){const X=m.x(x);s+=svgEl('line',{x1:X,y1:m.T,x2:X,y2:m.T+m.H,class:x===0?'svg-axis':'svg-grid'});s+=svgEl('text',{x:X,y:m.T+m.H+17,'text-anchor':'middle',class:'svg-tick'},`${x}°`)}
  const yTicks=c.fn==='tan'?[-4,-2,0,2,4]:[-1,-.5,0,.5,1];for(const y of yTicks){const Y=m.y(y),axis=Math.abs(y)<1e-9;s+=svgEl('line',{x1:m.L,y1:Y,x2:m.L+m.W,y2:Y,class:axis?'svg-axis':'svg-grid'});s+=svgEl('text',{x:m.L-8,y:Y+3,'text-anchor':'end',class:'svg-tick'},String(y))}
  if(c.fn==='tan')for(const a of [90,270]){const X=m.x(a);s+=svgEl('line',{x1:X,y1:m.T,x2:X,y2:m.T+m.H,class:'svg-asymptote'});s+=svgEl('text',{x:X+4,y:m.T+13,class:'svg-asymptote-label'},'asymptote')}
  const targetY=m.y(c.target),sols=solutions(c),rightSolution=sols.some(v=>v>330);if(targetY>=m.T-1&&targetY<=m.T+m.H+1){s+=svgEl('line',{x1:m.L,y1:targetY,x2:m.L+m.W,y2:targetY,class:'svg-target'});s+=svgEl('text',{x:m.L+m.W-6,y:targetY+(rightSolution?16:-7),'text-anchor':'end',class:'svg-target-label'},`target y = ${c.targetText}`)}
  for(const d of tracePaths(m,c)){s+=svgEl('path',{d,class:'svg-trace-under'});s+=svgEl('path',{d,class:'svg-trace'})}
  const currentV=trig(c.fn,state.angle),cursorX=m.x(state.angle);s+=svgEl('line',{x1:cursorX,y1:m.T,x2:cursorX,y2:m.T+m.H,class:'svg-cursor'});if(Number.isFinite(currentV)&&currentV>=m.yMin&&currentV<=m.yMax)s+=svgEl('circle',{cx:cursorX,cy:m.y(currentV),r:6,class:'svg-live-dot'});
  for(const sol of sols){if(!(state.discovered.has(String(sol))||state.complete))continue;const X=m.x(sol),Y=m.y(c.target);if(Y<m.T-1||Y>m.T+m.H+1)continue;s+=svgEl('circle',{cx:X,cy:Y,r:6,class:'svg-solution-dot'});const anchor=sol>320?'end':sol<35?'start':'middle',dx=sol>320?-7:sol<35?7:0;s+=svgEl('text',{x:X+dx,y:Y-11,'text-anchor':anchor,class:'svg-solution-label'},`${fmt(sol,1)}°`)}
  s+=svgEl('text',{x:m.L+8,y:m.T+17,class:'svg-title'},`y = ${c.fn} x`);s+=svgEl('text',{x:m.L+8,y:m.T+29,class:'svg-sub'},c.fn==='tan'?'two 180° branches in this interval':'one 360° cycle in this interval');s+=svgEl('text',{x:m.L+m.W/2,y:h-4,'text-anchor':'middle',class:'svg-axis-label'},'x / degrees');
  svg.setAttribute('viewBox',`0 0 ${w} ${h}`);svg.innerHTML=s;
}
$('graphSvg').style.setProperty('--lab-chart-text-size','12px');
function draw(){renderGraph();$('valuePill').textContent=fmtValue(trig(currentCase().fn,state.angle));}
draw();
// Replay a full native sine trace, revealing both target crossings as they are visited.
return time=>{const angle=359.5*Math.max(0,Math.min(1,(time-500)/7000));
  if(angle<lastAngle){state.visited.fill(0);state.discovered.clear();state.complete=false;state.fullTurns=0;lastAngle=0;}
  if(angle>lastAngle)markUnwrappedSegment(lastAngle,angle);
  state.angle=angle;lastAngle=angle;draw();};

})();
let lastTime;
return time=>{if(time===lastTime)return;lastTime=time;root.host.style.setProperty('--preview-animation-time',String(time));update(time);};
}
