import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import path from 'node:path';
import test from 'node:test';
import {fileURLToPath} from 'node:url';
import {extractEmbeddedLabContract,parseLabContractV1} from '../tools/lab-contract/index.ts';

const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const slug='straight-line-coordinates-equations';
const sourcePath=path.join(root,'labs-src/mathematics',slug,'lab.html');
const contractPath=path.join(root,'lab-contracts/mathematics',`${slug}.lab.json`);
const outputPath=path.join(root,'public/labs/mathematics',`${slug}.html`);

const count=(text:string,needle:string)=>text.split(needle).length-1;

test('visual-discovery canary is a normal canonical lab package',async()=>{
  const [source,contractText,output]=await Promise.all([
    readFile(sourcePath,'utf8'),readFile(contractPath,'utf8'),readFile(outputPath,'utf8')
  ]);
  const contract=parseLabContractV1(contractText,contractPath);

  assert.equal(count(source,'<main'),1,'source must have one main');
  assert.match(source,/<body\b[^>]*class="[^"]*lab-adopt-v3[^"]*"/);
  assert.match(source,/<main\b[^>]*data-lab-workspace/);
  assert.match(source,/data-lab-resource="lab-kit\.css"/);
  assert.match(source,/data-lab-resource="lab-kit\.js"/);
  assert.equal(count(source,'<!-- LAB_DESIGN_COMPONENTS -->'),1);
  assert.doesNotMatch(source,/data-examplicity-lab-contract|LAB_CONTRACT_START/,'contract belongs in the sidecar before publication');
  assert.doesNotMatch(source,/public\/developer\/lab-kit|vendor\/lab-kit/,'authored lab must not reach into shared-resource implementation paths');
  assert.match(source,/data-lab-role="model"/);
  assert.match(source,/data-lab-manipulative="graph"/);
  assert.match(source,/data-lab-role="working"/);
  assert.match(source,/data-lab-role="evidence"/);
  assert.match(source,/data-lab-action="advance"/);

  assert.deepEqual(extractEmbeddedLabContract(output),contract,'publication must inject the exact sidecar');
  assert.match(output,/LAB_RESOURCE_START id="lab-kit\.css"/);
  assert.match(output,/LAB_RESOURCE_START id="lab-kit\.js"/);
  assert.doesNotMatch(output,/<(?:link|script)[^>]+(?:href|src)="\.\/lab-kit\.(?:css|js)"/);

  const experimentalBuild=await readFile(path.join(root,'experiments/visual-discovery/build.mjs'),'utf8');
  assert.doesNotMatch(experimentalBuild,/straight-lines\.pilot\.json/,'canonical canary must not also be generated by the experiment compiler');
});
