export const exams = ['0478', '9618'] as const;
export type ExamCode = (typeof exams)[number];

export const subjects = [
  {
    id: 'computer-science',
    name: 'Computer Science',
    headerLabel: 'Cambridge Computer Science',
    exams,
  },
] as const;
export type SubjectId = (typeof subjects)[number]['id'];

export type Activity = {
  slug: string;
  title: string;
  description: string;
  kind: 'lab' | 'tool';
  href: string;
};

export type Lab = Activity & {
  subject: SubjectId;
  topic: string;
  format: string;
  exams: ExamCode[];
};

export const translator: Lab = {
  subject: 'computer-science',
  slug: 'translator',
  title: 'Pseudocode ↔ Python',
  description: 'Write, synchronize, run and trace Cambridge-style pseudocode alongside Python.',
  topic: 'Programming',
  format: 'Code translator',
  kind: 'tool',
  exams: ['0478', '9618'],
  href: '/labs/translator.html',
};

export const labs: Lab[] = [
  {
    subject: 'computer-science',
    slug: 'binary-numbers',
    title: 'Binary Number Practice',
    description: 'Build fluency with binary and hexadecimal registers through generated GCSE and AS questions.',
    topic: 'Data representation',
    format: 'Practice',
    kind: 'lab',
    exams: ['0478', '9618'],
    href: '/labs/binary-numbers.html',
  },
  {
    subject: 'computer-science',
    slug: 'bitmap-compression',
    title: 'Bitmap Compression',
    description: 'Paint a bitmap, change its colour depth, and compare normal, RLE and Huffman encoding.',
    topic: 'Data representation',
    format: 'Visual experiment',
    kind: 'lab',
    exams: ['0478', '9618'],
    href: '/labs/bitmap-compression.html',
  },
  {
    subject: 'computer-science',
    slug: 'sound-sampling',
    title: 'Digital Sound Sampling',
    description: 'Change sample rate and resolution, then compare the reconstructed signal visually and by listening.',
    topic: 'Data representation',
    format: 'Signal lab',
    kind: 'lab',
    exams: ['0478', '9618'],
    href: '/labs/sound-sampling.html',
  },
  {
    subject: 'computer-science',
    slug: 'huffman-rover',
    title: 'Huffman Rover',
    description: 'Design variable-length codes, decode a binary transmission and guide a rover across Mars.',
    topic: 'Data representation',
    format: 'Coding challenge',
    kind: 'lab',
    exams: ['9618'],
    href: '/labs/huffman-rover.html',
  },
  {
    subject: 'computer-science',
    slug: 'parity-arq',
    title: 'Parity & ARQ Transmission',
    description: 'Corrupt frames in flight and watch parity detection and automatic repeat requests respond.',
    topic: 'Networks & communication',
    format: 'Protocol lab',
    kind: 'lab',
    exams: ['0478', '9618'],
    href: '/labs/parity-arq.html',
  },
  {
    subject: 'computer-science',
    slug: 'network-topology',
    title: 'Network Topology Builder',
    description: 'Build bus, star, mesh and hybrid networks, then send packets through your design.',
    topic: 'Networks & communication',
    format: 'Network builder',
    kind: 'lab',
    exams: ['9618'],
    href: '/labs/network-topology.html',
  },
  {
    subject: 'computer-science',
    slug: 'csma-cd',
    title: 'Ethernet CSMA/CD',
    description: 'Control three stations on a shared cable and observe collision detection and backoff.',
    topic: 'Networks & communication',
    format: 'Network simulation',
    kind: 'lab',
    exams: ['9618'],
    href: '/labs/csma-cd.html',
  },
  {
    subject: 'computer-science',
    slug: 'encryption-eavesdropper',
    title: 'Symmetric and Asymmetric Encryption',
    description: 'Place keys with Bob or Eve, then compare who can read the same open or encrypted interception.',
    topic: 'Networks & communication',
    format: 'Key experiment',
    kind: 'lab',
    exams: ['0478'],
    href: '/labs/encryption-eavesdropper.html',
  },
  {
    subject: 'computer-science',
    slug: 'dns-url-retrieval',
    title: 'Web Page Retrieval',
    description: 'Repair DNS records and watch each mapping determine the requested server and returned page.',
    topic: 'Web & internet',
    format: 'DNS experiment',
    kind: 'lab',
    exams: ['0478'],
    href: '/labs/dns-url-retrieval.html',
  },
  {
    subject: 'computer-science',
    slug: 'cookies-state-jar',
    title: 'Session and Persistent Cookies',
    description: 'Choose a cookie lifetime, then close and restart the browser to test what persists.',
    topic: 'Web & internet',
    format: 'Cookie experiment',
    kind: 'lab',
    exams: ['0478'],
    href: '/labs/cookies-state-jar.html',
  },
  {
    subject: 'computer-science',
    slug: 'fetch-decode-execute',
    title: 'Fetch–Decode–Execute',
    description: 'Advance one clock tick at a time and follow data across CPU pathways and system buses.',
    topic: 'Processors & memory',
    format: 'CPU simulator',
    kind: 'lab',
    exams: ['0478', '9618'],
    href: '/labs/fetch-decode-execute.html',
  },
  {
    subject: 'computer-science',
    slug: 'assembly',
    title: 'Cambridge Assembly',
    description: 'Trace a Cambridge-style assembly program and follow every transfer through the processor.',
    topic: 'Processors & memory',
    format: 'Code tracer',
    kind: 'lab',
    exams: ['9618'],
    href: '/labs/assembly.html',
  },
  {
    subject: 'computer-science',
    slug: 'interrupt-service-routine',
    title: 'Interrupt Service Routine',
    description: 'Trigger a keyboard interrupt at different task steps and compare where processing resumes.',
    topic: 'Processors & memory',
    format: 'Interrupt model',
    kind: 'lab',
    exams: ['0478'],
    href: '/labs/interrupt-service-routine.html',
  },
  {
    subject: 'computer-science',
    slug: 'software-stack',
    title: 'Software Stack & Boot Process',
    description: 'Build the software layers, power on the system and test whether an application can run.',
    topic: 'System software',
    format: 'Systems model',
    kind: 'lab',
    exams: ['0478', '9618'],
    href: '/labs/software-stack.html',
  },
  {
    subject: 'computer-science',
    slug: 'memory-management',
    title: 'OS Memory Management',
    description: 'Create realistic workloads and watch pages move between storage, RAM, page file and cache.',
    topic: 'System software',
    format: 'OS simulation',
    kind: 'lab',
    exams: ['0478', '9618'],
    href: '/labs/memory-management.html',
  },
  {
    subject: 'computer-science',
    slug: 'normalization-workbench',
    title: 'Database Normalisation',
    description: 'Correct one tutor name in 1NF, 2NF and 3NF designs, then compare inconsistent copies.',
    topic: 'Databases & data modelling',
    format: 'Data model',
    kind: 'lab',
    exams: ['9618'],
    href: '/labs/normalization-workbench.html',
  },
  {
    subject: 'computer-science',
    slug: 'file-access-hash',
    title: 'File Organisation and Access',
    description: 'Run the same lookup and insertion through serial, sequential and hashed files.',
    topic: 'Databases & data modelling',
    format: 'Record access',
    kind: 'lab',
    exams: ['9618'],
    href: '/labs/file-access-hash.html',
  },
  {
    subject: 'computer-science',
    slug: 'graph-search-frontier',
    title: 'Dijkstra and A* Graph Search',
    description: 'Change an edge cost, then compare Dijkstra and A* routes, costs and visited nodes.',
    topic: 'Artificial intelligence',
    format: 'Graph search',
    kind: 'lab',
    exams: ['9618'],
    href: '/labs/graph-search-frontier.html',
  },
  {
    subject: 'computer-science',
    slug: 'expert-system-inference-trace',
    title: 'Expert System Rule Builder',
    description: 'Build an IF–THEN rule, test known cases, then validate it against an unseen case.',
    topic: 'Artificial intelligence',
    format: 'Rule builder',
    kind: 'lab',
    exams: ['0478'],
    href: '/labs/expert-system-inference-trace.html',
  },
  {
    subject: 'computer-science',
    slug: 'logic-circuit-builder',
    title: 'Logic Circuit Builder',
    description: 'Assign gates, toggle inputs and verify the circuit against every row of a target truth table.',
    topic: 'Logic & automated systems',
    format: 'Logic builder',
    kind: 'lab',
    exams: ['9618'],
    href: '/labs/logic-circuit-builder.html',
  },
  {
    subject: 'computer-science',
    slug: 'automation-chain-builder',
    title: 'Automation Chain Builder',
    description: 'Arrange a sensor, processor and heater, then test which chain responds correctly.',
    topic: 'Logic & automated systems',
    format: 'Control systems',
    kind: 'lab',
    exams: ['0478'],
    href: '/labs/automation-chain-builder.html',
  },
  {
    subject: 'computer-science',
    slug: 'state-transition-tracer',
    title: 'Ticket Gate State-Transition Diagram',
    description: 'Complete the gate diagram, then trigger events to observe state, output and barrier changes.',
    topic: 'Logic & automated systems',
    format: 'State model',
    kind: 'lab',
    exams: ['9618'],
    href: '/labs/state-transition-tracer.html',
  },
  {
    subject: 'computer-science',
    slug: 'blockchain-tamper-evidence',
    title: 'Blockchain Tamper Evidence',
    description: 'Change one transaction and watch the next saved link expose the mismatch.',
    topic: 'Security & distributed systems',
    format: 'Ledger experiment',
    kind: 'lab',
    exams: ['0478'],
    href: '/labs/blockchain-tamper-evidence.html',
  },
  translator,
];
